### ISSUE TITLE
Mostly uncommented source

### ISSUE THREAD

**Issue by falkecarlsen** [r00tman/corrupter#2]
Nice project, I really like the idea :+1: 

At c38d09d018bb908adcc7fde6aab818fee97df3a4, lines: 36, 79, 81, 82, and 153 to 167 contains code commented out. Most of the actual source remains uncommented.

I do realise that this project is mostly for fun, and as such, code quality is not prioritised as highly. However, I think it would help possible contributors to understand, and possibly extend the source.

**Comment by r00tman** [comment]
Thank you!

Yes, that's a very valid point that needs to be addressed.

I just tried to make some comments and clean up the code. You check out the last commit. I think that's much better than it was before. So, is the issue fixed, or more things could be done on the matter?
