### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by alrayyes** [r00tman/corrupter#5]
Hi,

Could you add a license file so I can commit this to AUR?

**Comment by alrayyes** [comment]
Package is [good to go](https://github.com/alrayyes/corrupter-arch-package) :)

**Comment by r00tman** [comment]
Hi! Thank you for the package :)

I just added a license file, so it should be good to go

**Comment by alrayyes** [comment]
Great, thanks!

**Comment by alrayyes** [comment]
[Added](https://aur.archlinux.org/packages/corrupter-git/)!

**Comment by r00tman** [comment]
Awesome!

Should I mention it on reddit or you'd like to?

**Comment by alrayyes** [comment]
Go ahead and mention it.

**Comment by r00tman** [comment]
Thanks. You are u/alrayyes, right?

**Comment by alrayyes** [comment]
Yes

**Comment by r00tman** [comment]
[Done](https://old.reddit.com/r/unixporn/comments/b4jopw/oc_portable_image_corrupter_for_i3locklock/ej71w8w/)!
