### ISSUE TITLE
Can corrupter-bin be added?

### ISSUE THREAD

**Issue by marcospb19** [r00tman/corrupter#9]
> Thanks for `corrupter`!

Every time i configure a new system, i install the _corrupter-git_ package, but it takes a while to download _Go_ (470 MB), can you add a binary file on the repository or on the releases (tags) sections?

Just like `yay-bin`, people prefer to just skip the Go installation process.

If i'm not already asking too much, can corrupter-bin have an dedicated _aur package_? i saw the PKGBUILD from corrupter-git (as a example), and i think that i could maintain it.

**Comment by r00tman** [comment]
Sure, that'd be awesome!

Just ping me back after it's done, so I could add it to the readme.

**Comment by r00tman** [comment]
So, I added the x86_64 binaries [there](https://github.com/r00tman/corrupter/releases/tag/v1.0), since `yay-bin` and other `*-bin` packages download their binaries from github too.

**Comment by marcospb19** [comment]
Ok I'll do it as soon as I can
